# fly.toml app configuration file generated for job-application-tracker on 2024-08-01T16:14:17+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'job-application-tracker'
primary_region = 'iad'

[build]

[experimental]
    auto_rollback = true

[mounts]
    source = 'jat_machine'
    destination = '/mnt/'
    initial_size = 1

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
