# fly.toml app configuration file generated for job-application-tracker on 2024-08-01T16:14:17+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'job-application-tracker'
primary_region = 'iad'

[build]

[experimental]
    auto_rollback = true

[mounts]
    source = 'jat_machine'
    destination = '/mnt/'
    initial_size = 1

[[services]]
    internal_port = 3000
    processes = [ "app" ]
    protocol = "tcp"
    auto_stop_machines = "suspend"
    auto_start_machines = true

[[services.ports]]
    force_https = true
    handlers = [ "http" ]
    port = 80

[[services.ports]]
    handlers = [ "tls", "http" ]
    port = 443

[[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[vm]]
  size = 'shared-cpu-1x'
